// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYLGA5dTmLonWzwnw86xL4OgYK-1COe4',
    appId: '1:985221152437:web:210d9c37cb8d23330688fc',
    messagingSenderId: '985221152437',
    projectId: 'watch-hub-e6f06',
    authDomain: 'watch-hub-e6f06.firebaseapp.com',
    databaseURL: 'https://watch-hub-e6f06-default-rtdb.firebaseio.com',
    storageBucket: 'watch-hub-e6f06.firebasestorage.app',
    measurementId: 'G-89V914WV4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLeCbCgAO3kC_1kXw7nbYQTvMZO8D9fQA',
    appId: '1:985221152437:android:2570cebf198201450688fc',
    messagingSenderId: '985221152437',
    projectId: 'watch-hub-e6f06',
    databaseURL: 'https://watch-hub-e6f06-default-rtdb.firebaseio.com',
    storageBucket: 'watch-hub-e6f06.firebasestorage.app',
  );
}
